/*
===========================================================================

Return to Castle Wolfenstein single player GPL Source Code
Copyright (C) 1999-2010 id Software LLC, a ZeniMax Media company. 

This file is part of the Return to Castle Wolfenstein single player GPL Source Code (RTCW SP Source Code).  

RTCW SP Source Code is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

RTCW SP Source Code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RTCW SP Source Code.  If not, see <http://www.gnu.org/licenses/>.

In addition, the RTCW SP Source Code is also subject to certain additional terms. You should have received a copy of these additional terms immediately following the terms and conditions of the GNU General Public License which accompanied the RTCW SP Source Code.  If not, please request a copy in writing from id Software at the address below.

If you have questions concerning this license or the applicable additional terms, you may contact in writing id Software LLC, c/o ZeniMax Media Inc., Suite 120, Rockville, Maryland 20850 USA.

===========================================================================
*/

#pragma once

#include "ai_cast.h"
#include "g_save.h"

extern void G_RetrieveMoveSpeedsFromClient ( int entnum , const char * text ) ;
extern void ClientDisconnect ( int clientNum ) ;
extern void ClientSpawn ( GameEntity * ent ) ;
extern void ClientBegin ( int clientNum ) ;
extern const char * ClientConnect ( int clientNum , bool firstTime , bool isBot ) ;
extern void ClientUserinfoChanged ( int clientNum ) ;
extern bool G_ParseAnimationFiles ( char * modelname , GameClient * cl ) ;
extern bool G_GetModelInfo ( int clientNum , char * modelName , animModelInfo_t * * modelInfo ) ;
extern bool G_CheckForExistingModelInfo ( GameClient * cl , char * modelName , animModelInfo_t * * modelInfo ) ;



extern void respawn ( GameEntity * ent ) ;

extern void SetClientViewAngle ( GameEntity * ent , vec3_t angle ) ;
extern void CopyToBodyQue ( GameEntity * ent ) ;
extern void BodySink ( GameEntity * ent ) ;
extern void InitBodyQue ( void ) ;
extern GameEntity * SelectSpectatorSpawnPoint ( vec3_t origin , vec3_t angles ) ;
extern GameEntity * SelectInitialSpawnPoint ( vec3_t origin , vec3_t angles ) ;
extern GameEntity * SelectSpawnPoint ( vec3_t avoidPoint , vec3_t origin , vec3_t angles ) ;
extern GameEntity * SelectRandomDeathmatchSpawnPoint ( void ) ;
extern GameEntity * SelectNearestDeathmatchSpawnPoint ( vec3_t from ) ;
extern bool SpotWouldTelefrag ( GameEntity * spot ) ;
extern void SP_info_player_intermission ( GameEntity * ent ) ;
extern void SP_info_player_start ( GameEntity * ent ) ;
extern void SP_info_player_deathmatch ( GameEntity * ent ) ;
extern bool G_RadiusDamage ( vec3_t origin , GameEntity * attacker , float damage , float radius , GameEntity * ignore , int mod ) ;
extern bool CanDamage ( GameEntity * targ , vec3_t origin ) ;
extern void G_Damage ( GameEntity * targ , GameEntity * inflictor , GameEntity * attacker , vec3_t dir , vec3_t point , int damage , int dflags , int mod ) ;
extern void G_ArmorDamage ( GameEntity * targ ) ;
extern bool IsHeadShot ( GameEntity * targ , GameEntity * attacker , vec3_t dir , vec3_t point , int mod ) ;
extern bool IsHeadShotWeapon ( int mod , GameEntity * targ , GameEntity * attacker ) ;
extern int CheckArmor ( GameEntity * ent , int damage , int dflags ) ;
extern void player_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int meansOfDeath ) ;
extern void body_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int meansOfDeath ) ;
extern void GibEntity ( GameEntity * self , int killer ) ;
extern void GibHead ( GameEntity * self , int killer ) ;
extern void LookAtKiller ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker ) ;
extern void TossClientItems ( GameEntity * self ) ;
extern void AddScore ( GameEntity * ent , int score ) ;
extern bool AICast_ScriptAction_CatchFire ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_PushAway ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_AnimCondition ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_LockPlayer ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ExplicitRouting ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MusicQueue ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MusicFade ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MusicStop ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MusicPlay ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MusicStart ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Cvar ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_NoTarget ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SetHealth ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_AIScriptName ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_EntityScriptName ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Parachute ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Cigarette ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_StopCam ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_StopCamBlack ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_StartCamBlack ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_StartCam ( cast_state_t * cs , char * params ) ;
extern bool ScriptStartCam ( cast_state_t * cs , char * params , bool black ) ;
extern bool AICast_ScriptAction_Zoom ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_KnockBack ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_StateType ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_RestoreScript ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_BackupScript ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Headlook ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_LightningDamage ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_DenyAction ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Attrib ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Avoid ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_NoAvoid ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Sight ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_NoSight ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_FoundSecret ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ChangeLevel ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_EndGame ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Teleport ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SavePersistant ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Unmount ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Mount ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ResetScript ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_FaceTargetAngles ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Print ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_NoAIDamage ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ObjectiveMet ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ObjectivesNeeded ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_MissionFailed ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SpawnCast ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Accum ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GodMode ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_FireAtTarget ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SaveGame ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_AlertEntity ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Movetype ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GiveInventory ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_TakeWeapon ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GiveWeapon ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GiveArmor ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SetArmor ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SelectWeapon ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SuggestWeapon ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SetClip ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_SetAmmo ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_ClearAnim ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_PlayAnim ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Attack ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_NoAttack ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_PlaySound ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_FollowCast ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Trigger ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_Wait ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_AbortIfLoadgame ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_CrouchToCast ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_WalkToCast ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GotoCast ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_CrouchToMarker ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_WalkToMarker ( cast_state_t * cs , char * params ) ;
extern bool AICast_ScriptAction_GotoMarker ( cast_state_t * cs , char * params ) ;
extern void AICast_NoAttackIfNotHurtSinceLastScriptAction ( cast_state_t * cs ) ;


extern void SP_target_rumble ( GameEntity * self ) ;
extern void target_rumble_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void target_rumble_think ( GameEntity * ent ) ;
extern void SP_target_script_trigger ( GameEntity * ent ) ;
extern void target_script_trigger_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_smoke ( GameEntity * ent ) ;
extern void smoke_init ( GameEntity * ent ) ;
extern void smoke_toggle ( GameEntity * ent , GameEntity * self , GameEntity * activator ) ;
extern void smoke_think ( GameEntity * ent ) ;
extern void SP_target_alarm ( GameEntity * ent ) ;
extern void Use_Target_Alarm ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_lock ( GameEntity * ent ) ;
extern void Use_Target_Lock ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_autosave ( GameEntity * ent ) ;
extern void SP_target_counter ( GameEntity * ent ) ;
extern void SP_target_fog ( GameEntity * ent ) ;
extern void Use_target_fog ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Use_Target_Counter ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Use_Target_Autosave ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_location ( GameEntity * self ) ;
extern void target_location_linkup ( GameEntity * ent ) ;
extern void SP_target_position ( GameEntity * self ) ;
extern void SP_target_kill ( GameEntity * self ) ;
extern void target_kill_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_relay ( GameEntity * self ) ;
extern void relay_AIScript_AlertEntity ( GameEntity * self ) ;
extern void target_relay_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_teleporter ( GameEntity * self ) ;
extern void target_teleporter_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_laser ( GameEntity * self ) ;
extern void target_laser_start ( GameEntity * self ) ;
extern void target_laser_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void target_laser_off ( GameEntity * self ) ;
extern void target_laser_on ( GameEntity * self ) ;
extern void target_laser_think ( GameEntity * self ) ;
extern void SP_target_speaker ( GameEntity * ent ) ;
extern void target_speaker_multiple ( GameEntity * ent ) ;
extern void Use_Target_Speaker ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_print ( GameEntity * ent ) ;
extern void Use_Target_Print ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_score ( GameEntity * ent ) ;
extern void Use_Target_Score ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_delay ( GameEntity * ent ) ;
extern void Use_Target_Delay ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Think_Target_Delay ( GameEntity * ent ) ;
extern void SP_target_remove_powerups ( GameEntity * ent ) ;
extern void Use_target_remove_powerups ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_target_give ( GameEntity * ent ) ;
extern void Use_Target_Give ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void PM_AdjustAimSpreadScale ( void ) ;
extern void PM_CoolWeapons ( void ) ;
extern int PM_WeaponClipEmpty ( int wp ) ;
extern int PM_WeaponAmmoAvailable ( int wp ) ;
extern void PM_WeaponUseAmmo ( int wp , int amount ) ;

extern void PM_AddFallEvent ( int landing , int surfaceparms ) ;
extern void PM_ClipVelocity ( vec3_t in , vec3_t normal , vec3_t out , float overbounce ) ;
extern void PM_AddTouchEnt ( int entityNum ) ;
extern void PM_AddEvent ( int newEvent ) ;
extern float Com_GetFlamethrowerRange ( void ) ;
extern float BG_AnimGetFootstepGap ( PlayerState * ps , float xyspeed ) ;
extern void BG_AnimUpdatePlayerStateConditions ( pmove_t * pmove ) ;
extern animation_t * BG_GetAnimationForIndex ( int client , int index ) ;
extern int BG_GetAnimScriptEvent ( PlayerState * ps , scriptAnimEventTypes_t event ) ;
extern int BG_GetAnimScriptAnimation ( int client , aistateEnum_t estate , scriptAnimMoveTypes_t movetype ) ;
extern int BG_GetConditionValue ( int client , int condition , bool checkConversion ) ;
extern void BG_UpdateConditionValueStrings ( int client , const char * conditionStr , const char * valueStr ) ;
extern void BG_UpdateConditionValue ( int client , int condition , int value , bool checkConversion ) ;
extern char * BG_GetAnimString ( int client , int anim ) ;
extern bool BG_ValidAnimScript ( int clientNum ) ;
extern int BG_AnimScriptEvent ( PlayerState * ps , scriptAnimEventTypes_t event , bool isContinue , bool force ) ;
extern int BG_AnimScriptStateChange ( PlayerState * ps , aistateEnum_t newState , aistateEnum_t oldState ) ;
extern int BG_AnimScriptCannedAnimation ( PlayerState * ps , aistateEnum_t state ) ;
extern int BG_AnimScriptAnimation ( PlayerState * ps , aistateEnum_t estate , scriptAnimMoveTypes_t movetype , bool isContinue ) ;
extern int BG_ExecuteCommand ( PlayerState * ps , animScriptCommand_t * scriptCommand , bool setTimer , bool isContinue , bool force ) ;
extern int BG_PlayAnimName ( PlayerState * ps , const char * animName , animBodyPart_t bodyPart , bool setTimer , bool isContinue , bool force ) ;
extern int BG_PlayAnim ( PlayerState * ps , int animNum , animBodyPart_t bodyPart , int forceDuration , bool setTimer , bool isContinue , bool force ) ;
extern animScriptItem_t * BG_FirstValidItem ( int client , animScript_t * script ) ;
extern bool BG_EvaluateConditions ( int client , animScriptItem_t * scriptItem ) ;
extern void BG_AnimParseAnimScript ( animModelInfo_t * modelInfo , animScriptData_t * scriptData , int client , char * filename , char * input ) ;
extern void BG_ParseCommands ( const char * * input , animScriptItem_t * scriptItem , animModelInfo_t * modelInfo , animScriptData_t * scriptData ) ;
extern bool BG_ParseConditions ( const char * * text_pp , animScriptItem_t * scriptItem ) ;
extern void BG_ParseConditionBits ( const char * * text_pp , animStringItem_t * stringTable , int condIndex , int result [ 2 ] ) ;
extern bool BG_AnimParseAnimConfig ( animModelInfo_t * animModelInfo , const char * filename , const char * input ) ;
extern void BG_InitWeaponStrings ( void ) ;
extern char * BG_CopyStringIntoBuffer ( const char * string , char * buffer , int bufSize , int * offset ) ;
extern int BG_IndexForString ( const char * token , animStringItem_t * strings , bool allowFail ) ;
extern animation_t * BG_AnimationForString ( const char * string , animModelInfo_t * modelInfo ) ;
extern int BG_AnimationIndexForString ( const char * string , int client ) ;
extern animModelInfo_t * BG_ModelInfoForModelname ( const char * modelname ) ;
extern animModelInfo_t * BG_ModelInfoForClient ( int client ) ;

extern bool G_ScriptAction_SetHealth ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_RestoreScript ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_BackupScript ( GameEntity * ent , char * params ) ;

extern bool G_ScriptAction_AIScriptName ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_EntityScriptName ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_StartCam ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_StopSound ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_Halt ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_TagConnect ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_ResetScript ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_FaceAngles ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_Print ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MissionSuccess ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MissionFailed ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_Accum ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_AlertEntity ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_PlayAnim ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MusicQueue ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MusicFade ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MusicStop ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MusicPlay ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_MusicStart ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_PlaySound ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_Trigger ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_Wait ( GameEntity * ent , char * params ) ;
extern bool G_ScriptAction_GotoMarker ( GameEntity * ent , char * params ) ;
extern void Info_SetValueForKey_Big ( char * s , const char * key , const char * value ) ;
extern void Info_SetValueForKey ( char * s , const char * key , const char * value ) ;
extern bool Info_Validate ( const char * s ) ;
extern void Info_RemoveKey_Big ( char * s , const char * key ) ;
extern void Info_RemoveKey ( char * s , const char * key ) ;
extern void Info_NextPair ( const char * * head , char * key , char * value ) ;
extern const char * Info_ValueForKey ( const char * s , const char * key ) ;
extern float * tv ( float x , float y , float z ) ;
extern char *  va ( const char * format , ... ) ;
extern int Q_strcasecmp ( const char * s1 , const char * s2 ) ;
extern int Q_strncasecmp ( const char * s1 , const char * s2 , int n ) ;
extern char * Q_CleanStr ( char * string ) ;
extern int Q_PrintStrlen ( const char * string ) ;
extern void Q_strcat ( char * dest , int size , const char * src ) ;
extern char * Q_strupr ( char * s1 ) ;
extern char * Q_strlwr ( char * s1 ) ;
extern int Q_stricmp ( const char * s1 , const char * s2 ) ;
extern int Q_strncmp ( const char * s1 , const char * s2 , size_t n ) ;
extern int Q_stricmpn ( const char * s1 , const char * s2 , size_t n ) ;
extern void Q_strncpyz ( char * dest , const char * src , size_t destsize ) ;
extern char * Q_strrchr ( const char * string , int c ) ;
extern int Q_isforfilename ( int c ) ;
extern int Q_isalphanumeric ( int c ) ;
extern int Q_isnumeric ( int c ) ;
extern int Q_isalpha ( int c ) ;
extern int Q_isupper ( int c ) ;
extern int Q_islower ( int c ) ;
extern int Q_isprint ( int c ) ;
extern void Parse3DMatrix ( const char * * buf_p , int z , int y , int x , float * m ) ;
extern void Parse2DMatrix ( const char * * buf_p , int y , int x , float * m ) ;
extern void Parse1DMatrix ( const char * * buf_p , int x , float * m ) ;
extern void SkipRestOfLine ( const char * * data ) ;
extern void SkipBracedSection (const char * * program ) ;
extern void COM_MatchToken ( const char * * buf_p , const char * match ) ;
extern char * COM_ParseExt ( const char ** data_p , bool allowLineBreaks ) ;
extern int COM_Compress ( char * data_p ) ;
extern const char * SkipWhitespace ( const char * data , bool * hasNewLines ) ;
extern void COM_ParseWarning ( char * format , ... ) ;
extern void COM_ParseError ( char * format , ... ) ;
extern char * COM_Parse ( const char * * data_p ) ;
extern int COM_GetCurrentParseLine ( void ) ;
extern void COM_SetCurrentParseLine ( int line ) ;
extern void COM_RestoreParseSession ( const char * * data_p ) ;
extern void COM_BeginParseSession ( const char * name ) ;
extern void Swap_Init ( void ) ;
extern float FloatNoSwap ( float f ) ;
extern float FloatSwap ( float f ) ;
extern qint64 Long64NoSwap ( qint64 ll ) ;
extern qint64 Long64Swap ( qint64 ll ) ;
extern int LongNoSwap ( int l ) ;
extern int LongSwap ( int l ) ;
extern short ShortNoSwap ( short l ) ;
extern short ShortSwap ( short l ) ;
extern float LittleFloat ( float l ) ;
extern float BigFloat ( float l ) ;
extern qint64 LittleLong64 ( qint64 l ) ;
extern qint64 BigLong64 ( qint64 l ) ;
extern int LittleLong ( int l ) ;
extern int BigLong ( int l ) ;
extern short LittleShort ( short l ) ;
extern short BigShort ( short l ) ;
extern void COM_BitClear ( int array [ ] , int bitNum ) ;
extern void COM_BitSet ( int array [ ] , int bitNum ) ;
extern bool COM_BitCheck ( const int array [ ] , int bitNum ) ;
extern void COM_DefaultExtension ( char * path , int maxSize , const char * extension ) ;
extern void COM_StripFilename ( const char * in , char * out ) ;
extern void COM_StripExtension ( const char * in , char * out ) ;
extern char * COM_SkipPath ( char * pathname ) ;
extern float Com_Clamp ( float min , float max , float value ) ;


extern bool G_BotConnect ( int clientNum , bool restart ) ;
extern void G_QueueBotBegin ( int clientNum ) ;

extern void G_WriteSessionData ( void ) ;

extern void G_InitSessionData ( GameClient * client , char * userinfo ) ;
extern void G_ReadSessionData ( GameClient * client ) ;
extern void G_WriteClientSessionData ( GameClient * client ) ;
extern const char * AIFunc_DefaultStart ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Battle ( cast_state_t * cs ) ;
extern const char * AIFunc_GrenadeKickStart ( cast_state_t * cs ) ;
extern const char * AIFunc_GrenadeKick ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectBodyStart ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectBody ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleMG42Start ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleMG42 ( cast_state_t * cs ) ;
extern const char * AIFunc_GrenadeFlushStart ( cast_state_t * cs ) ;
extern const char * AIFunc_GrenadeFlush ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleTakeCoverStart ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleTakeCover ( cast_state_t * cs ) ;
extern const char * AIFunc_AvoidDangerStart ( cast_state_t * cs ) ;
extern const char * AIFunc_AvoidDanger ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleChaseStart ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleChase ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleAmbushStart ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleAmbush ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleHuntStart ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleHunt ( cast_state_t * cs ) ;
extern const char * AIFunc_FlipMoveStart ( cast_state_t * cs , vec3_t vec ) ;
extern const char * AIFunc_FlipMove ( cast_state_t * cs ) ;
extern const char * AIFunc_BattleDiveStart ( cast_state_t * cs , vec3_t vec ) ;
extern const char * AIFunc_BattleRollStart ( cast_state_t * cs , vec3_t vec ) ;
extern const char * AIFunc_BattleRoll ( cast_state_t * cs ) ;
extern const char * AIFunc_DoorMarkerStart ( cast_state_t * cs , int doornum , int markernum ) ;
extern const char * AIFunc_DoorMarker ( cast_state_t * cs ) ;
extern const char * AIFunc_ChaseGoalStart ( cast_state_t * cs , int entitynum , float reachdist , bool slowApproach ) ;
extern const char * AIFunc_ChaseGoal ( cast_state_t * cs ) ;
extern const char * AIFunc_ChaseGoalIdleStart ( cast_state_t * cs , int entitynum , float reachdist ) ;
extern const char * AIFunc_ChaseGoalIdle ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectAudibleEventStart ( cast_state_t * cs , int entnum ) ;
extern const char * AIFunc_InspectAudibleEvent ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectBulletImpactStart ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectBulletImpact ( cast_state_t * cs ) ;
extern const char * AIFunc_InspectFriendlyStart ( cast_state_t * cs , int entnum ) ;
extern const char * AIFunc_InspectFriendly ( cast_state_t * cs ) ;
extern const char * AIFunc_IdleStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Idle ( cast_state_t * cs ) ;
extern void AICast_SpecialFunc ( cast_state_t * cs ) ;
extern float AICast_SpeedScaleForDistance ( cast_state_t * cs , float startdist , float idealDist ) ;
extern bot_moveresult_t * AICast_MoveToPos ( cast_state_t * cs , vec3_t pos , int entnum ) ;
extern float AICast_GetRandomViewAngle ( cast_state_t * cs , float tracedist ) ;
extern const char * AIFunc_Restore ( cast_state_t * cs ) ;
extern GameEntity * fire_mortar ( GameEntity * self , vec3_t start , vec3_t dir ) ;
extern bool visible ( GameEntity * self , GameEntity * other ) ;
extern void fire_lead ( GameEntity * self , vec3_t start , vec3_t dir , int damage ) ;
extern GameEntity * fire_flamebarrel ( GameEntity * self , vec3_t start , vec3_t dir ) ;
extern GameEntity * fire_crowbar ( GameEntity * self , vec3_t start , vec3_t dir ) ;
extern GameEntity * fire_zombiespirit ( GameEntity * self , GameEntity * bolt , vec3_t start , vec3_t dir ) ;
extern GameEntity * fire_zombiespit ( GameEntity * self , vec3_t start , vec3_t dir ) ;
extern GameEntity * fire_rocket ( GameEntity * self , vec3_t start , vec3_t dir ) ;
extern GameEntity * fire_grenade ( GameEntity * self , vec3_t start , vec3_t dir , int grenadeWPID ) ;
extern void G_RunCrowbar ( GameEntity * ent ) ;
extern void G_RunSpit ( GameEntity * ent ) ;
extern int G_PredictMissile ( GameEntity * ent , int duration , vec3_t endPos , bool allowBounce ) ;
extern void G_PredictBounceMissile ( GameEntity * ent , trajectory_t * pos , trace_t * trace , int time ) ;
extern void G_RunMissile ( GameEntity * ent ) ;
extern void G_ExplodeMissilePoisonGas ( GameEntity * ent ) ;
extern void G_MissileDie ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void G_ExplodeMissile ( GameEntity * ent ) ;
extern void M_think ( GameEntity * ent ) ;
extern void Concussive_fx ( vec3_t origin ) ;
extern void Concussive_think ( GameEntity * ent ) ;
extern void G_MissileImpact ( GameEntity * ent , trace_t * trace , int impactDamage , vec3_t dir ) ;
extern bool G_BounceMissile ( GameEntity * ent , trace_t * trace ) ;
extern int DebugLine ( vec3_t start , vec3_t end , int color ) ;
extern void G_ProcessTagConnect ( GameEntity * ent , bool clearAngles ) ;
extern bool infront ( GameEntity * self , GameEntity * other ) ;
extern void G_SetAngle ( GameEntity * ent , vec3_t angle ) ;
extern void G_SetOrigin ( GameEntity * ent , vec3_t origin ) ;
extern void G_AnimScriptSound ( int soundIndex , vec3_t org , int client ) ;
extern void G_Sound ( GameEntity * ent , int soundIndex ) ;
extern void G_AddEvent ( GameEntity * ent , int event , int eventParm ) ;
extern void G_AddPredictableEvent ( GameEntity * ent , int event , int eventParm ) ;
extern void G_KillBox ( GameEntity * ent ) ;
extern GameEntity * G_TempEntity ( vec3_t origin , int event ) ;
extern void G_FreeEntity ( GameEntity * ed ) ;
extern bool G_EntitiesFree ( void ) ;
extern GameEntity * G_Spawn ( void ) ;
extern void G_InitGentity ( GameEntity * e ) ;
extern void G_SetMovedir ( vec3_t angles , vec3_t movedir ) ;
extern char * vtosf ( const vec3_t v ) ;
extern char * vtos ( const vec3_t v ) ;
extern void G_UseTargets ( GameEntity * ent , GameEntity * activator ) ;
extern GameEntity * G_PickTarget ( char * targetname ) ;
extern GameEntity * G_Find ( GameEntity * from , int fieldofs , const char * match ) ;

extern int G_SoundIndex ( const char * name ) ;
extern int G_ModelIndex ( const char * name ) ;
extern int G_FindConfigstringIndex ( const char * name , int start , int max , bool create ) ;
extern const char * BuildShaderStateConfig ( ) ;
extern void AddRemap ( const char * oldShader , const char * newShader , float timeOffset ) ;
extern void SP_ai_trigger ( GameEntity * ent ) ;
extern void ai_trigger_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void ai_trigger_activate ( GameEntity * self ) ;
extern void AICast_Touch_Trigger ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void AICast_trigger_trigger ( GameEntity * ent , GameEntity * activator ) ;
extern void AICast_trigger_wait ( GameEntity * ent ) ;
extern void SP_ai_effect ( GameEntity * ent ) ;
extern void ai_effect_think ( GameEntity * ent ) ;
extern void SP_ai_marker ( GameEntity * ent ) ;
extern void SP_trigger_objective_info ( GameEntity * ent ) ;
extern void Touch_objective_info ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;


extern void SP_gas ( GameEntity * self ) ;
extern void gas_think ( GameEntity * ent ) ;
extern void gas_touch ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_trigger_aidoor ( GameEntity * ent ) ;
extern void trigger_aidoor_stayopen ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_trigger_deathCheck ( GameEntity * ent ) ;
extern void SP_trigger_once ( GameEntity * ent ) ;
extern void SP_func_timer ( GameEntity * self ) ;
extern void func_timer_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void func_timer_think ( GameEntity * self ) ;
extern void SP_trigger_hurt ( GameEntity * self ) ;
extern void hurt_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void hurt_think ( GameEntity * ent ) ;
extern void hurt_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_trigger_teleport ( GameEntity * self ) ;
extern void trigger_teleporter_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_target_push ( GameEntity * self ) ;
extern void Use_target_push ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void SP_trigger_push ( GameEntity * self ) ;
extern void trigger_push_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void AimAtTarget ( GameEntity * self ) ;
extern void trigger_push_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_trigger_always ( GameEntity * ent ) ;
extern void trigger_always_think ( GameEntity * ent ) ;
extern void SP_trigger_multiple ( GameEntity * ent ) ;
extern void Enable_Trigger_Touch ( GameEntity * ent ) ;
extern void Touch_Multi ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void Use_Multi ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void multi_trigger ( GameEntity * ent , GameEntity * activator ) ;
extern void multi_wait ( GameEntity * ent ) ;
extern void InitTrigger ( GameEntity * self ) ;
extern void AICast_AudibleEvent ( int srcnum , vec3_t pos , float range ) ;
extern void AICast_ProcessBullet ( GameEntity * attacker , vec3_t start , vec3_t end ) ;
extern bool AICast_AllowFlameDamage ( int entNum ) ;
extern bool AICast_HasFiredWeapon ( int entNum , int weapon ) ;
extern void AICast_CheckDangerousEntity ( GameEntity * ent , int dangerFlags , float dangerDist , float tacticalLevel , float aggressionLevel , bool hurtFriendly ) ;
extern int AICast_SafeMissileFire ( GameEntity * ent , int duration , int enemyNum , vec3_t enemyPos , int selfNum , vec3_t endPos ) ;
extern bool AICast_WantToRetreat ( cast_state_t * cs ) ;
extern float AICast_GetAccuracy ( int entnum ) ;
extern bool AICast_StopAndAttack ( cast_state_t * cs ) ;
extern float AICast_GetWeaponSoundRange ( int weapon ) ;
extern void AICast_RecordWeaponFire ( GameEntity * ent ) ;
extern bool AICast_AIDamageOK ( cast_state_t * cs , cast_state_t * ocs ) ;
extern bool AICast_GetTakeCoverPos ( cast_state_t * cs , int enemyNum , vec3_t enemyPos , vec3_t returnPos ) ;
extern void AICast_ProcessAttack ( cast_state_t * cs ) ;
extern bool AICast_RandomTriggerRelease ( cast_state_t * cs ) ;
extern bool AICast_CanMoveWhileFiringWeapon ( int weaponnum ) ;
extern bool AICast_AimAtEnemy ( cast_state_t * cs ) ;
extern void AICast_WeaponSway ( cast_state_t * cs , vec3_t ofs ) ;
extern bot_moveresult_t AICast_CombatMove ( cast_state_t * cs , int tfl ) ;
extern int AICast_WantsToTakeCover ( cast_state_t * cs , bool attacking ) ;
extern int AICast_WantsToChase ( cast_state_t * cs ) ;
extern float AICast_Aggression ( cast_state_t * cs ) ;
extern void AICast_ChooseWeapon ( cast_state_t * cs , bool battleFunc ) ;
extern bool AICast_WeaponUsable ( cast_state_t * cs , int weaponNum ) ;
extern bool AICast_GotEnoughAmmoForWeapon ( cast_state_t * cs , int weapon ) ;
extern float AICast_WeaponWantScale ( cast_state_t * cs , int weapon ) ;
extern void AICast_UpdateBattleInventory ( cast_state_t * cs , int enemy ) ;
extern bool AICast_CheckAttack ( cast_state_t * cs , int enemy , bool allowHitWorld ) ;
extern bool AICast_CheckAttackAtPos ( int entnum , int enemy , vec3_t pos , bool ducking , bool allowHitWorld ) ;
extern bool AICast_CheckAttack_real ( cast_state_t * cs , int enemy , bool allowHitWorld ) ;
extern float AICast_WeaponRange ( cast_state_t * cs , int weaponnum ) ;
extern bool AICast_SameTeam ( cast_state_t * cs , int enemynum ) ;
extern bool AICast_QueryEnemy ( cast_state_t * cs , int enemynum ) ;
extern bool AICast_HostileEnemy ( cast_state_t * cs , int enemynum ) ;
extern bool AICast_EntityVisible ( cast_state_t * cs , int enemynum , bool directview ) ;
extern int AICast_ScanForEnemies ( cast_state_t * cs , int * enemies ) ;
extern bool AICast_StateChange ( cast_state_t * cs , aistateEnum_t newaistate ) ;
extern void FireWeapon ( GameEntity * ent ) ;
extern void CalcMuzzlePoints ( GameEntity * ent , int weapon ) ;
extern void CalcMuzzlePointForActivate ( GameEntity * ent , vec3_t forward , vec3_t right , vec3_t up , vec3_t muzzlePoint ) ;
extern void CalcMuzzlePoint ( GameEntity * ent , int weapon , vec3_t forward , vec3_t right , vec3_t up , vec3_t muzzlePoint ) ;
extern bool LogAccuracyHit ( GameEntity * target , GameEntity * attacker ) ;
extern void AddLean ( GameEntity * ent , vec3_t point ) ;
extern void Weapon_LightningFire ( GameEntity * ent ) ;
extern void Weapon_RocketLauncher_Fire ( GameEntity * ent , float aimSpreadScale ) ;
extern void weapon_venom_fire ( GameEntity * ent , bool fullmode , float aimSpreadScale ) ;
extern void VenomPattern ( vec3_t origin , vec3_t origin2 , int seed , GameEntity * ent ) ;
extern bool VenomPellet ( vec3_t start , vec3_t end , GameEntity * ent ) ;
extern void weapon_zombiespirit ( GameEntity * ent , GameEntity * missile ) ;
extern void weapon_zombiespit ( GameEntity * ent ) ;
extern GameEntity * weapon_grenadelauncher_fire ( GameEntity * ent , int grenType ) ;
extern GameEntity * weapon_crowbar_throw ( GameEntity * ent ) ;
extern void Bullet_Fire_Extended ( GameEntity * source , GameEntity * attacker , vec3_t start , vec3_t end , float spread , int damage , int recursion ) ;
extern void Bullet_Fire ( GameEntity * ent , float spread , int damage ) ;
extern void Bullet_Endpos ( GameEntity * ent , float spread , vec3_t * end ) ;
extern void SniperSoundEFX ( vec3_t pos ) ;
extern void EmitterCheck ( GameEntity * ent , GameEntity * attacker , trace_t * tr ) ;
extern void RubbleFlagCheck ( GameEntity * ent , trace_t tr ) ;
extern void Tesla_Fire ( GameEntity * ent ) ;
extern void Cross_Fire ( GameEntity * ent ) ;
extern float G_GetWeaponSpread ( int weapon ) ;
extern int G_GetWeaponDamage ( int weapon ) ;
extern void SnapVectorTowards ( vec3_t v , vec3_t to ) ;
extern trace_t * CheckMeleeAttack ( GameEntity * ent , float dist , bool isTest ) ;
extern void Weapon_Gauntlet ( GameEntity * ent ) ;


extern void Weapon_Knife ( GameEntity * ent ) ;
extern bool AICast_ScriptRun ( cast_state_t * cs , bool force ) ;
extern void AICast_ForceScriptEvent ( struct cast_state_s * cs ,const char * eventStr ,const char * params ) ;
extern void AICast_ScriptEvent ( struct cast_state_s * cs , const char * eventStr , const char * params ) ;
extern void AICast_ScriptChange ( cast_state_t * cs , int newScriptNum ) ;
extern void AICast_ScriptParse ( cast_state_t * cs ) ;
extern void AICast_ScriptLoad ( void ) ;
extern cast_script_stack_action_t * AICast_ActionForString ( cast_state_t * cs , char * string ) ;
extern int AICast_EventForString ( char * string ) ;
extern bool AICast_EventMatch_IntInRange ( cast_script_event_t * event , const char * eventParm ) ;
extern bool AICast_EventMatch_StringEqual ( cast_script_event_t * event , const char * eventParm ) ;
extern const char * AIFunc_Heinrich_SpawnSpiritsStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_RaiseDeadStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_RaiseDead ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_MeleeStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_Earthquake ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordSideSlashStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordSideSlash ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordKnockbackStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordKnockback ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordLungeStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Heinrich_SwordLunge ( cast_state_t * cs ) ;
extern void AICast_Heinrich_Taunt ( cast_state_t * cs ) ;
extern void AICast_Heinrich_SoundPrecache ( void ) ;
extern const char * AIFunc_FlameZombie_PortalStart ( cast_state_t * cs ) ;
extern const char * AIFunc_FlameZombie_Portal ( cast_state_t * cs ) ;
extern const char * AIFunc_Helga_MeleeStart ( cast_state_t * cs ) ;
extern const char * AIFunc_Helga_Melee ( cast_state_t * cs ) ;
extern const char * AIFunc_Helga_SpiritAttack_Start ( cast_state_t * cs ) ;
extern const char * AIFunc_Helga_SpiritAttack ( cast_state_t * cs ) ;
extern void AICast_DBG_Cmd_f ( int clientNum ) ;
extern void AICast_DBG_Spawn_f ( GameClient * client , char * cmd ) ;
extern void AICast_DBG_RouteTable_f ( vec3_t org , char * param ) ;
extern void AICast_DebugFrame ( cast_state_t * cs ) ;
extern void AICast_DBG_ListAIFuncs ( cast_state_t * cs , int numprint ) ;
extern void AICast_DBG_AddAIFunc ( cast_state_t * cs , const char * funcname ) ;
extern void AICast_DBG_InitAIFuncs ( void ) ;
extern void AICast_SightUpdate ( int numchecks ) ;
extern void AICast_UpdateNonVisibility ( GameEntity * srcent , GameEntity * destent , bool directview ) ;
extern void AICast_UpdateVisibility ( GameEntity * srcent , GameEntity * destent , bool shareVis , bool directview ) ;
extern bool AICast_CheckVisibility ( GameEntity * srcent , GameEntity * destent ) ;
extern bool AICast_VisibleFromPos ( vec3_t srcpos , int srcnum , vec3_t destpos , int destnum , bool updateVisPos ) ;
extern bool AICast_InFieldOfVision ( vec3_t viewangles , float fov , vec3_t angles ) ;

extern void SP_script_camera ( GameEntity * ent ) ;
extern void SP_script_model_med ( GameEntity * ent ) ;
extern void script_model_med_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void script_model_med_spawn ( GameEntity * ent ) ;
extern void SP_script_mover ( GameEntity * ent ) ;
extern void script_mover_blocked ( GameEntity * ent , GameEntity * other ) ;
extern void script_mover_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void script_mover_spawn ( GameEntity * ent ) ;
extern void script_mover_pain ( GameEntity * self , GameEntity * attacker , int damage , vec3_t point ) ;
extern void script_mover_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void script_linkentity ( GameEntity * ent ) ;
extern bool G_Script_ScriptRun ( GameEntity * ent ) ;
extern void G_Script_ScriptEvent ( GameEntity * ent , const char * eventStr , const char * params ) ;
extern void G_Script_ScriptChange ( GameEntity * ent , int newScriptNum ) ;
extern void G_Script_ScriptParse ( GameEntity * ent ) ;
extern void G_Script_ScriptLoad ( void ) ;
extern g_script_stack_action_t * G_Script_ActionForString ( const char * string ) ;
extern int G_Script_EventForString ( const char * string ) ;
extern bool G_Script_EventMatch_IntInRange ( g_script_event_t * event , char * eventParm ) ;
extern bool G_Script_EventMatch_StringEqual ( g_script_event_t * event , char * eventParm ) ;
extern void SP_props_flamethrower ( GameEntity * ent ) ;
extern void props_flamethrower_init ( GameEntity * ent ) ;
extern void props_flamethrower_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void props_flamethrower_think ( GameEntity * ent ) ;
extern void SP_props_footlocker ( GameEntity * self ) ;
extern void props_locker_death ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_locker_mass ( GameEntity * ent ) ;
extern void props_locker_spawn_item ( GameEntity * ent ) ;
extern void init_locker ( GameEntity * ent ) ;
extern void props_locker_pain ( GameEntity * ent , GameEntity * attacker , int damage , vec3_t point ) ;
extern void props_locker_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void props_locker_endrattle ( GameEntity * ent ) ;
extern void Spawn_Junk ( GameEntity * ent ) ;
extern void SP_props_statueBRUSH ( GameEntity * self ) ;
extern void SP_props_statue ( GameEntity * ent ) ;
extern void props_statue_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void props_statue_death ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_statue_animate ( GameEntity * ent ) ;
extern void props_statue_blocked ( GameEntity * ent ) ;
extern void SP_skyportal ( GameEntity * ent ) ;
extern void SP_props_decor_Scale ( GameEntity * ent ) ;
extern void SP_props_decorBRUSH ( GameEntity * self ) ;
extern void SP_props_decoration ( GameEntity * ent ) ;
extern void props_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void Use_props_decoration ( GameEntity * ent , GameEntity * self , GameEntity * activator ) ;
extern void props_decoration_death ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_decoration_animate ( GameEntity * ent ) ;
extern void SP_props_ExploPart ( GameEntity * ent ) ;
extern void props_ExploPartInit ( GameEntity * ent ) ;
extern void props_ExploPartUse ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_propsFireColumn ( GameEntity * ent ) ;
extern void propsFireColumnInit ( GameEntity * ent ) ;
extern void propsFireColumnUse ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_props_snowGenerator ( GameEntity * ent ) ;
extern void props_snowGenerator_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void props_snowGenerator_think ( GameEntity * ent ) ;
extern void SP_props_castlebed ( GameEntity * ent ) ;
extern void props_castlebed_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_castlebed_animate ( GameEntity * ent ) ;
extern void props_castlebed_touch ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_Props_58x112tablew ( GameEntity * ent ) ;
extern void props_58x112tablew_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_58x112tablew_think ( GameEntity * ent ) ;
extern void SP_Props_Flipping_Table ( GameEntity * ent ) ;
extern void props_flippy_blocked ( GameEntity * ent , GameEntity * other ) ;
extern void props_flippy_table_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void flippy_table_animate ( GameEntity * ent ) ;
extern void flippy_table_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_Props_Crate32x64 ( GameEntity * ent ) ;
extern void props_crate32x64_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_crate32x64_think ( GameEntity * ent ) ;
extern void SP_crate_32 ( GameEntity * self ) ;
extern void SP_crate_64 ( GameEntity * self ) ;
extern void crate_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void crate_animate ( GameEntity * ent ) ;
extern void touch_crate_64 ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_Props_Flamebarrel ( GameEntity * ent ) ;
extern void Props_Barrel_Think ( GameEntity * self ) ;
extern void Props_OilSlickSlippery ( GameEntity * ent ) ;
extern void Props_Barrel_Die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void OilSlick_remove ( GameEntity * ent ) ;
extern void OilSlick_remove_think ( GameEntity * ent ) ;
extern void Props_Barrel_Pain ( GameEntity * ent , GameEntity * attacker , int damage , vec3_t point ) ;
extern void SP_OilParticles ( GameEntity * ent ) ;
extern bool validOilSlickSpawnPoint ( vec3_t point , GameEntity * ent ) ;
extern void Delayed_Leak_Think ( GameEntity * ent ) ;
extern void OilParticles_think ( GameEntity * ent ) ;
extern void SP_OilSlick ( GameEntity * ent ) ;
extern void smoker_think ( GameEntity * ent ) ;
extern void barrel_smoke ( GameEntity * ent ) ;
extern void Props_Barrel_Animate ( GameEntity * ent ) ;
extern void Props_Barrel_Touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_Props_Desklamp ( GameEntity * ent ) ;
extern void SP_props_shard_generator ( GameEntity * ent ) ;
extern void Use_Props_Shard_Generator ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_Props_DamageInflictor ( GameEntity * ent ) ;
extern void Use_DamageInflictor ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_Props_ChairHiback ( GameEntity * ent ) ;
extern void SP_Props_ChairSide ( GameEntity * ent ) ;
extern void SP_Props_ChairChatArm ( GameEntity * ent ) ;
extern void SP_Props_ChairChat ( GameEntity * ent ) ;
extern void SP_Props_GenericChair ( GameEntity * ent ) ;
extern void SP_Props_Chair ( GameEntity * ent ) ;
extern void Props_Chair_Skyboxtouch ( GameEntity * ent ) ;
extern void Props_Chair_Die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void Prop_Break_Sound ( GameEntity * ent ) ;
extern void Spawn_Shard ( GameEntity * ent , GameEntity * inflictor , int quantity , int type ) ;
extern void Props_Chair_Animate ( GameEntity * ent ) ;
extern void Props_Chair_Touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void Prop_Check_Ground ( GameEntity * self ) ;
extern bool Prop_Touch ( GameEntity * self , GameEntity * other , vec3_t v ) ;
extern void Props_Chair_Think ( GameEntity * self ) ;
extern void Props_Activated ( GameEntity * self ) ;
extern void Props_TurnLightsOff ( GameEntity * self ) ;
extern void Just_Got_Thrown ( GameEntity * self ) ;
extern void SP_Props_Locker_Tall ( GameEntity * ent ) ;
extern void props_locker_tall_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void locker_tall_think ( GameEntity * ent ) ;
extern void SP_Props_RadioSEVEN ( GameEntity * ent ) ;
extern void props_radio_dieSEVEN ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void SP_Props_Radio ( GameEntity * ent ) ;
extern void props_radio_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void SP_Props_Bench ( GameEntity * ent ) ;
extern void props_bench_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void props_bench_think ( GameEntity * ent ) ;
extern void InitProp ( GameEntity * ent ) ;
extern void propExplosion ( GameEntity * ent ) ;
extern void propExplosionLarge ( GameEntity * ent ) ;
extern void SP_Dust ( GameEntity * ent ) ;
extern void dust_angles_think ( GameEntity * ent ) ;
extern void dust_use ( GameEntity * ent , GameEntity * self , GameEntity * activator ) ;
extern void SP_SmokeDust ( GameEntity * ent ) ;
extern void smokedust_use ( GameEntity * ent , GameEntity * self , GameEntity * activator ) ;
extern void SP_props_gunsparks ( GameEntity * ent ) ;
extern void SP_props_sparks ( GameEntity * ent ) ;
extern void sparks_angles_think ( GameEntity * ent ) ;
extern void Psparks_think ( GameEntity * ent ) ;
extern void PGUNsparks_use ( GameEntity * ent , GameEntity * self , GameEntity * activator ) ;
extern void prop_smoke ( GameEntity * ent ) ;
extern void Psmoke_think ( GameEntity * ent ) ;
extern void SP_props_box_64 ( GameEntity * self ) ;
extern void touch_props_box_64 ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_props_box_48 ( GameEntity * self ) ;
extern void touch_props_box_48 ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_props_box_32 ( GameEntity * self ) ;
extern void touch_props_box_32 ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void moveit ( GameEntity * ent , float yaw , float dist ) ;
extern void DropToFloor ( GameEntity * ent ) ;
extern void DropToFloorG ( GameEntity * ent ) ;

extern void trap_BotResetWeaponState ( int weaponstate ) ;
extern void trap_BotFreeWeaponState ( int weaponstate ) ;
extern int trap_BotAllocWeaponState ( void ) ;
extern int trap_BotLoadWeaponWeights ( int weaponstate , char * filename ) ;
extern void trap_BotGetWeaponInfo ( int weaponstate , int weapon , void * weaponinfo ) ;
extern int trap_BotChooseBestFightWeapon ( int weaponstate , int * inventory ) ;
extern void trap_BotInitAvoidReach ( int handle ) ;
extern void trap_BotInitMoveState ( int handle , void * initmove ) ;
extern void trap_BotFreeMoveState ( int handle ) ;
extern int trap_BotAllocMoveState ( void ) ;
extern int trap_BotPredictVisiblePosition ( vec3_t origin , int areanum , void * goal , int travelflags , vec3_t target ) ;
extern int trap_BotMovementViewTarget ( int movestate , void * goal , int travelflags , float lookahead , vec3_t target ) ;
extern int trap_BotReachabilityArea ( vec3_t origin , int testground ) ;
extern void trap_BotResetLastAvoidReach ( int movestate ) ;
extern void trap_BotResetAvoidReach ( int movestate ) ;
extern int trap_BotMoveInDirection ( int movestate , vec3_t dir , float speed , int type ) ;
extern void trap_BotMoveToGoal ( void * result , int movestate , void * goal , int travelflags ) ;
extern void trap_BotResetMoveState ( int movestate ) ;
extern void trap_BotFreeGoalState ( int handle ) ;
extern int trap_BotAllocGoalState ( int state ) ;
extern void trap_BotMutateGoalFuzzyLogic ( int goalstate , float range ) ;

extern void trap_BotFreeItemWeights ( int goalstate ) ;
extern int trap_BotLoadItemWeights ( int goalstate , char * filename ) ;
extern void trap_BotUpdateEntityItems ( void ) ;
extern void trap_BotInitLevelItems ( void ) ;
extern float trap_BotAvoidGoalTime ( int goalstate , int number ) ;
extern int trap_BotGetMapLocationGoal ( char * name , void * goal ) ;
extern int trap_BotGetNextCampSpotGoal ( int num , void * goal ) ;
extern int trap_BotGetLevelItemGoal ( int index , const char * classname , void * goal ) ;
extern int trap_BotItemGoalInVisButNotVisible ( int viewer , vec3_t eye , vec3_t viewangles , void * goal ) ;
extern int trap_BotTouchingGoal ( vec3_t origin , void * goal ) ;
extern int trap_BotChooseNBGItem ( int goalstate , vec3_t origin , int * inventory , int travelflags , void * ltg , float maxtime ) ;
extern int trap_BotChooseLTGItem ( int goalstate , vec3_t origin , int * inventory , int travelflags ) ;
extern int trap_BotGetSecondGoal ( int goalstate , void * goal ) ;
extern int trap_BotGetTopGoal ( int goalstate , void * goal ) ;
extern void trap_BotGoalName ( int number , char * name , int size ) ;
extern void trap_BotDumpGoalStack ( int goalstate ) ;
extern void trap_BotDumpAvoidGoals ( int goalstate ) ;
extern void trap_BotEmptyGoalStack ( int goalstate ) ;
extern void trap_BotPopGoal ( int goalstate ) ;
extern void trap_BotPushGoal ( int goalstate , void * goal ) ;
extern void trap_BotRemoveFromAvoidGoals ( int goalstate , int number ) ;
extern void trap_BotResetAvoidGoals ( int goalstate ) ;
extern void trap_BotResetGoalState ( int goalstate ) ;

extern void trap_Characteristic_String ( int character , int index , char * buf , int size ) ;
extern int trap_Characteristic_BInteger ( int character , int index , int min , int max ) ;
extern int trap_Characteristic_Integer ( int character , int index ) ;
extern float trap_Characteristic_BFloat ( int character , int index , float min , float max ) ;
extern float trap_Characteristic_Float ( int character , int index ) ;
extern void trap_BotFreeCharacter ( int character ) ;
extern int trap_BotLoadCharacter ( char * charfile , int skill ) ;
extern void trap_EA_ResetInput ( int client , void * init ) ;
extern void trap_EA_GetInput ( int client , float thinktime , void * input ) ;
extern void trap_EA_EndRegular ( int client , float thinktime ) ;
extern void trap_EA_View ( int client , vec3_t viewangles ) ;
extern void trap_EA_Move ( int client , vec3_t dir , float speed ) ;
extern void trap_EA_MoveRight ( int client ) ;
extern void trap_EA_MoveLeft ( int client ) ;
extern void trap_EA_MoveBack ( int client ) ;
extern void trap_EA_MoveForward ( int client ) ;
extern void trap_EA_MoveDown ( int client ) ;
extern void trap_EA_MoveUp ( int client ) ;
extern void trap_EA_Crouch ( int client ) ;
extern void trap_EA_DelayedJump ( int client ) ;
extern void trap_EA_Jump ( int client ) ;
extern void trap_EA_Respawn ( int client ) ;
extern void trap_EA_Use ( int client ) ;
extern void trap_EA_Reload ( int client ) ;
extern void trap_EA_Attack ( int client ) ;
extern void trap_EA_Talk ( int client ) ;
extern void trap_EA_SelectWeapon ( int client , int weapon ) ;
extern void trap_EA_Command ( int client , char * command ) ;
extern void trap_EA_Gesture ( int client ) ;
extern void trap_EA_DropInv ( int client , char * inv ) ;
extern void trap_EA_UseInv ( int client , char * inv ) ;
extern void trap_EA_DropItem ( int client , char * it ) ;
extern void trap_EA_UseItem ( int client , char * it ) ;
extern void trap_EA_SayTeam ( int client , char * str ) ;
extern void trap_EA_Say ( int client , char * str ) ;
extern void trap_AAS_SetAASBlockingEntity ( vec3_t absmin , vec3_t absmax , int blocking ) ;
extern bool trap_AAS_GetRouteFirstVisPos ( vec3_t srcpos , vec3_t destpos , int travelflags , vec3_t retpos ) ;
extern int trap_AAS_FindAttackSpotWithinRange ( int srcnum , int rangenum , int enemynum , float rangedist , int travelflags , float * outpos ) ;
extern bool trap_AAS_RT_GetHidePos ( vec3_t srcpos , int srcnum , int srcarea , vec3_t destpos , int destnum , int destarea , vec3_t returnPos ) ;
extern void trap_AAS_RT_ShowRoute ( vec3_t srcpos , int srcnum , int destnum ) ;
extern int trap_AAS_PredictClientMovement ( void * move , int entnum , vec3_t origin , int presencetype , int onground , vec3_t velocity , vec3_t cmdmove , int cmdframes , int maxframes , float frametime , int stopevent , int stopareanum , int visualize ) ;
extern int trap_AAS_Swimming ( vec3_t origin ) ;
extern int trap_AAS_AreaTravelTimeToGoalArea ( int areanum , vec3_t origin , int goalareanum , int travelflags ) ;
extern int trap_AAS_AreaReachability ( int areanum ) ;
extern int trap_AAS_IntForBSPEpairKey ( int ent , const char * key , int * value ) ;
extern int trap_AAS_FloatForBSPEpairKey ( int ent , const char * key , float * value ) ;
extern int trap_AAS_VectorForBSPEpairKey ( int ent , const char * key , vec3_t v ) ;
extern int trap_AAS_ValueForBSPEpairKey ( int ent , const char * key , char * value , int size ) ;
extern int trap_AAS_NextBSPEntity ( int ent ) ;
extern int trap_AAS_PointContents ( vec3_t point ) ;
extern int trap_AAS_TraceAreas ( vec3_t start , vec3_t end , int * areas , vec3_t * points , int maxareas ) ;
extern int trap_AAS_PointAreaNum ( vec3_t point ) ;
extern float trap_AAS_Time ( void ) ;
extern void trap_AAS_PresenceTypeBoundingBox ( int presencetype , vec3_t mins , vec3_t maxs ) ;
extern int trap_AAS_Initialized ( void ) ;
extern void trap_AAS_EntityInfo ( int entnum , void * info ) ;
extern void trap_BotUserCommand ( int clientNum , UserCmd * ucmd ) ;
extern int trap_BotGetServerCommand ( int clientNum , char * message , int size ) ;
extern int trap_BotGetSnapshotEntity ( int clientNum , int sequence ) ;
extern int trap_BotLibUpdateEntity ( int ent , void * bue ) ;
extern int trap_BotLibLoadMap ( const char * mapname ) ;
extern int trap_BotLibStartFrame ( float time ) ;
extern int trap_BotLibDefine ( char * string ) ;
extern int trap_BotLibVarGet ( const char * var_name , char * value , int size ) ;
extern int trap_BotLibVarSet ( const char * var_name , const char * value ) ;
extern int trap_BotLibShutdown ( void ) ;

extern bool CG_GetTag ( int clientNum , const char * tagName , orientation_t * orientation ) ;
extern void trap_SnapVector ( float * v ) ;
extern time_t trap_RealTime ( qtime_t * qtime ) ;
extern void trap_DebugPolygonDelete ( int id ) ;
extern int trap_DebugPolygonCreate ( int color , int numPoints , vec3_t * points ) ;

extern void Cvar_Update ( vmCvar_t * cvar ) ;


extern int FS_GetFileList ( const char * path , const char * extension , char * listbuf , int bufsize ) ;

extern void G_RunFrame ( int levelTime ) ;
extern void G_RunThink ( GameEntity * ent ) ;

extern void CheckReloadStatus ( void ) ;

extern void LogExit ( const char * string ) ;
extern void  G_LogPrintf ( const char * fmt , ... ) ;
extern void ExitLevel ( void ) ;

extern void FindIntermissionPoint ( void ) ;
extern void MoveClientToIntermission ( GameEntity * ent ) ;

extern void  Com_Printf ( const char * msg , ... ) ;
extern void  Com_Error ( int level , const char * error , ... ) ;
extern void G_ShutdownGame ( int restart ) ;
extern void G_InitGame ( int levelTime , int randomSeed , int restart ) ;
extern int G_SendMissionStats ( ) ;
extern void G_SpawnScriptCamera ( void ) ;
extern void G_UpdateCvars ( void ) ;
extern void G_RegisterCvars ( void ) ;
extern void G_RemapTeamShaders ( ) ;
extern void G_FindTeams ( void ) ;
extern void G_CheckForCursorHints ( GameEntity * ent ) ;
extern void G_EndGame ( void ) ;
extern bool G_canStealthStab ( int aiChar ) ;

extern void  Com_Printf ( const char * fmt , ... ) ;
extern void AICast_RegisterPain ( int entnum ) ;
extern int AICast_NumAttempts ( int entnum ) ;
extern int AICast_PlayTime ( int entnum ) ;
extern int AICast_NoReload ( int entnum ) ;
extern void AICast_AgePlayTime ( int entnum ) ;
extern void AICast_AdjustIdealYawForMover ( int entnum , float yaw ) ;
extern void G_SetAASBlockingEntity ( GameEntity * ent , bool blocking ) ;
extern void AICast_SetFlameDamage ( int entNum , bool status ) ;
extern bool AICast_NoFlameDamage ( int entNum ) ;
extern void AICast_Activate ( int activatorNum , int entNum ) ;
extern bool AICast_SolidsInBBox ( vec3_t pos , vec3_t mins , vec3_t maxs , int entnum , int mask ) ;
extern void AICast_CheckLoadGame ( void ) ;
extern void AICast_EnableRenderingThink ( GameEntity * ent ) ;
extern void AICast_CastScriptThink ( void ) ;
extern void AICast_DelayedSpawnCast ( GameEntity * ent , int castType ) ;
extern void AIChar_AIScript_AlertEntity ( GameEntity * ent ) ;
extern GameEntity * AICast_TravEntityForName ( GameEntity * startent , char * name ) ;
extern GameEntity * AICast_FindEntityForName ( const char * name ) ;
extern void AICast_Init ( void ) ;
extern GameEntity * AICast_CreateCharacter ( GameEntity * ent , float * attributes , cast_weapon_info_t * weaponInfo , const char * castname , const char * model , const char * head , const char * sex , const char * color , const char * handicap ) ;
extern void AICast_SetAASIndex ( cast_state_t * cs ) ;
extern void AICast_CheckLevelAttributes ( cast_state_t * cs , GameEntity * ent , const char * * ppStr ) ;
extern GameEntity * AICast_AddCastToGame ( GameEntity * ent , const char * castname , const char * model , const char * head , const char * sex , const char * color , const char * handicap ) ;
extern int AICast_ShutdownClient ( int client ) ;
extern int AICast_SetupClient ( int client ) ;
extern cast_state_t * AICast_GetCastState ( int entitynum ) ;
extern void AICast_Printf ( int type , const char * fmt , ... ) ;
extern void G_RunItem ( GameEntity * ent ) ;
extern void G_RunItemProp ( GameEntity * ent , vec3_t origin ) ;
extern void G_BounceItem ( GameEntity * ent , trace_t * trace ) ;
extern void G_SpawnItem ( GameEntity * ent , gitem_t * item ) ;
extern void SaveRegisteredItems ( void ) ;
extern void RegisterItem ( gitem_t * item ) ;
extern void ClearRegisteredItems ( void ) ;
extern void G_CheckTeamItems ( void ) ;
extern void FinishSpawningItem ( GameEntity * ent ) ;
extern void Use_Item ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern GameEntity * Drop_Item ( GameEntity * ent , gitem_t * item , float angle , bool novelocity ) ;
extern GameEntity * LaunchItem ( gitem_t * item , vec3_t origin , vec3_t velocity ) ;
extern void Touch_Item ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void Touch_Item_Auto ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void RespawnItem ( GameEntity * ent ) ;
extern int Pickup_Armor ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Health ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Weapon ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Ammo ( GameEntity * ent , GameEntity * other ) ;
extern void Add_Ammo ( GameEntity * ent , int weapon , int count , bool fillClip ) ;
extern void Fill_Clip ( PlayerState * ps , int weapon ) ;
extern int Pickup_Holdable ( GameEntity * ent , GameEntity * other ) ;
extern void UseHoldableItem ( GameEntity * ent , int item ) ;
extern int Pickup_Treasure ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Clipboard ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Key ( GameEntity * ent , GameEntity * other ) ;
extern int Pickup_Powerup ( GameEntity * ent , GameEntity * other ) ;
extern void BG_PlayerStateToEntityStateExtraPolate ( PlayerState * ps , EntityState * s , int time , bool snap ) ;
extern void BG_PlayerStateToEntityState ( PlayerState * ps , EntityState * s , bool snap ) ;
extern void BG_AddPredictableEventToPlayerstate ( int newEvent , int eventParm , PlayerState * ps ) ;
extern void BG_GetMarkDir ( const vec3_t dir , const vec3_t normal , vec3_t out ) ;
extern void BG_EvaluateTrajectoryDelta ( const trajectory_t * tr , int atTime , vec3_t result ) ;
extern void BG_EvaluateTrajectory ( const trajectory_t * tr , int atTime , vec3_t result ) ;
extern bool BG_CanItemBeGrabbed ( const EntityState * ent , const PlayerState * ps ) ;
extern bool isClipOnly ( int weap ) ;
extern bool BG_PlayerTouchesItem ( PlayerState * ps , EntityState * item , int atTime ) ;
extern gitem_t * BG_FindItem2 ( const char * name ) ;
extern gitem_t * BG_FindItem ( const char * pickupName ) ;
extern gitem_t * BG_FindItemForAmmo ( int ammo ) ;
extern gitem_t * BG_FindItemForKey ( wkey_t k , int * indexreturn ) ;
extern bool BG_AkimboFireSequence ( int weapon , int akimboClip , int coltClip ) ;
extern weapon_t BG_FindAmmoForWeapon ( weapon_t weapon ) ;
extern weapon_t BG_FindClipForWeapon ( weapon_t weapon ) ;
extern gitem_t * BG_FindItemForWeapon ( weapon_t weapon ) ;
extern gitem_t * BG_FindItemForHoldable ( holdable_t pw ) ;
extern gitem_t * BG_FindItemForPowerup ( powerup_t pw ) ;
extern void Svcmd_GameMem_f ( void ) ;
extern void G_InitMemory ( void ) ;
extern void * G_Alloc ( size_t size ) ;
extern void ClientCommand ( int clientNum ) ;
extern void Cmd_SetSpawnPoint_f ( GameEntity * clent ) ;
extern void Cmd_EntityCount_f ( GameEntity * ent ) ;
extern void Cmd_ClientDamage_f ( GameEntity * clent ) ;
extern void ClientDamage ( GameEntity * clent , int entnum , int enemynum , int id ) ;
extern int Cmd_WolfKick_f ( GameEntity * ent ) ;
extern void Cmd_Activate_f ( GameEntity * ent ) ;
extern bool G_ThrowChair ( GameEntity * ent , vec3_t dir , bool force ) ;
extern void Cmd_InterruptCamera_f ( GameEntity * ent ) ;
extern void Cmd_SetCameraOrigin_f ( GameEntity * ent ) ;
extern void Cmd_StopCamera_f ( GameEntity * ent ) ;
extern void Cmd_StartCamera_f ( GameEntity * ent ) ;
extern void Cmd_SetViewpos_f ( GameEntity * ent ) ;
extern bool G_canPickupMelee ( GameEntity * ent ) ;

extern void Cmd_Where_f ( GameEntity * ent ) ;


extern void Cmd_FollowCycle_f ( GameEntity * ent , int dir ) ;
extern void Cmd_Follow_f ( GameEntity * ent ) ;

extern void StopFollowing ( GameEntity * ent ) ;
extern void SetWolfData ( GameEntity * ent , char * ptype , char * weap , char * pistol , char * grenade , char * skinnum ) ;

extern void Cmd_Kill_f ( GameEntity * ent ) ;

extern void Cmd_Noclip_f ( GameEntity * ent ) ;
extern void Cmd_Notarget_f ( GameEntity * ent ) ;
extern void Cmd_Nofatigue_f ( GameEntity * ent ) ;
extern void Cmd_God_f ( GameEntity * ent ) ;
extern void Cmd_Give_f ( GameEntity * ent ) ;
extern void Cmd_Fogswitch_f ( void ) ;
extern void G_setfog ( char * fogstring ) ;
extern int ClientNumberFromString ( GameEntity * to , char * s ) ;
extern void SanitizeString ( char * in , char * out ) ;
extern char * ConcatArgs ( int start ) ;
extern bool CheatsOk ( GameEntity * ent ) ;


extern void SP_misc_firetrails ( GameEntity * ent ) ;
extern void misc_firetrails_finishspawning ( GameEntity * ent ) ;
extern void SP_misc_tagemitter ( GameEntity * ent ) ;
extern void misc_tagemitter_finishspawning ( GameEntity * ent ) ;
extern void tagemitter_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void tagemitter_die ( GameEntity * ent ) ;
extern void firetrail_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void firetrail_die ( GameEntity * ent ) ;
extern void SP_misc_spawner ( GameEntity * ent ) ;
extern void misc_spawner_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void misc_spawner_think ( GameEntity * ent ) ;
extern void SP_misc_flak ( GameEntity * self ) ;
extern void flak_spawn ( GameEntity * ent ) ;
extern void SP_mg42 ( GameEntity * self ) ;
extern void mg42_spawn ( GameEntity * ent ) ;
extern void mg42_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void mg42_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void mg42_think ( GameEntity * self ) ;
extern void Flak_Animate ( GameEntity * ent ) ;
extern void mg42_track ( GameEntity * self , GameEntity * other ) ;
extern void mg42_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void clamp_playerbehindgun ( GameEntity * self , GameEntity * other , vec3_t dang ) ;
extern void clamp_hweapontofirearc ( GameEntity * self , GameEntity * other , vec3_t dang ) ;
extern void Fire_Lead ( GameEntity * ent , GameEntity * activator , float spread , int damage ) ;
extern void mg42_muzzleflash ( GameEntity * ent , vec3_t muzzlepos ) ;
extern void flakPuff ( vec3_t origin , bool sky ) ;
extern void SP_Bubbles ( GameEntity * ent ) ;
extern void SP_Snow ( GameEntity * ent ) ;
extern void snow_think ( GameEntity * ent ) ;
extern void snowInPVS ( GameEntity * ent ) ;
extern void SP_dlight ( GameEntity * ent ) ;
extern void use_dlight ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void shutoff_dlight ( GameEntity * ent ) ;
extern void dlight_finish_spawning ( GameEntity * ent ) ;
extern void SP_corona ( GameEntity * ent ) ;
extern void use_corona ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_sniper_brush ( GameEntity * ent ) ;
extern void sniper_brush_init ( GameEntity * ent ) ;
extern void brush_activate_sniper ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_shooter_sniper ( GameEntity * ent ) ;
extern void SP_shooter_grenade ( GameEntity * ent ) ;
extern void SP_shooter_tesla ( GameEntity * ent ) ;
extern void shooter_tesla_finish_spawning ( GameEntity * ent ) ;
extern void use_shooter_tesla ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_shooter_zombiespit ( GameEntity * ent ) ;
extern void SP_shooter_rocket ( GameEntity * ent ) ;
extern void SP_shooter_mortar ( GameEntity * ent ) ;
extern void InitShooter ( GameEntity * ent , int weapon ) ;
extern void Use_Shooter ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_misc_portal_camera ( GameEntity * ent ) ;
extern void SP_misc_portal_surface ( GameEntity * ent ) ;
extern void locateCamera ( GameEntity * ent ) ;
extern void SP_misc_light_surface ( GameEntity * ent ) ;
extern void SP_misc_vis_dummy_multiple ( GameEntity * ent ) ;
extern void SP_misc_vis_dummy ( GameEntity * ent ) ;
extern void locateMaster ( GameEntity * ent ) ;
extern void SP_misc_gamemodel ( GameEntity * ent ) ;
extern void SP_misc_model ( GameEntity * ent ) ;
extern void SP_misc_spotlight ( GameEntity * ent ) ;
extern void spotlight_finish_spawning ( GameEntity * ent ) ;
extern void spotlight_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void use_spotlight ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_misc_grabber_trap ( GameEntity * ent ) ;
extern void grabber_wake_touch ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void grabber_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void grabber_wake ( GameEntity * ent ) ;
extern void grabber_pain ( GameEntity * ent , GameEntity * attacker , int damage , vec3_t point ) ;
extern void grabber_close ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void grabber_attack ( GameEntity * ent ) ;
extern void grabber_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void grabber_think_hit ( GameEntity * ent ) ;
extern void grabber_think_idle ( GameEntity * ent ) ;
extern void SP_misc_teleporter_dest ( GameEntity * ent ) ;
extern void TeleportPlayer ( GameEntity * player , vec3_t origin , vec3_t angles ) ;
extern void SP_lightJunior ( GameEntity * self ) ;
extern void SP_light ( GameEntity * self ) ;
extern void SP_info_notnull_big ( GameEntity * self ) ;
extern void SP_info_notnull ( GameEntity * self ) ;
extern void SP_info_null ( GameEntity * self ) ;
extern void SP_info_camp ( GameEntity * self ) ;
extern float VectorDistance ( vec3_t v1 , vec3_t v2 ) ;
extern void AxisToAngles ( vec3_t axis [ 3 ] , vec3_t angles ) ;
extern float vectoyaw ( const vec3_t vec ) ;
extern void ProjectPointOntoVector ( vec3_t point , vec3_t vStart , vec3_t vEnd , vec3_t vProj ) ;
extern void GetPerpendicularViewVector ( const vec3_t point , const vec3_t p1 , const vec3_t p2 , vec3_t up ) ;
extern void PerpendicularVector ( vec3_t dst , const vec3_t src ) ;
extern void AngleVectors ( const vec3_t angles , vec3_t forward , vec3_t right , vec3_t up ) ;
extern void MatrixMultiply ( float in1 [ 3 ] [ 3 ] , float in2 [ 3 ] [ 3 ] , float out [ 3 ] [ 3 ] ) ;
extern int Q_log2 ( int val ) ;
extern void Vector4Scale ( const vec4_t in , vec_t scale , vec4_t out ) ;
extern void VectorInverse ( vec3_t v ) ;
extern vec_t DistanceSquared ( const vec3_t p1 , const vec3_t p2 ) ;
extern vec_t Distance ( const vec3_t p1 , const vec3_t p2 ) ;
extern vec_t VectorLengthSquared ( const vec3_t v ) ;
extern vec_t VectorLength ( const vec3_t v ) ;
extern void CrossProduct ( const vec3_t v1 , const vec3_t v2 , vec3_t cross ) ;
extern void _VectorScale ( const vec3_t in , vec_t scale , vec3_t out ) ;
extern void _VectorCopy ( const vec3_t in , vec3_t out ) ;
extern void _VectorAdd ( const vec3_t veca , const vec3_t vecb , vec3_t out ) ;
extern void _VectorSubtract ( const vec3_t veca , const vec3_t vecb , vec3_t out ) ;
extern vec_t _DotProduct ( const vec3_t v1 , const vec3_t v2 ) ;
extern void _VectorMA ( const vec3_t veca , float scale , const vec3_t vecb , vec3_t vecc ) ;
extern vec_t VectorNormalize2 ( const vec3_t v , vec3_t out ) ;
extern void VectorNormalizeFast ( vec3_t v ) ;
extern vec_t VectorNormalize ( vec3_t v ) ;
extern int VectorCompare ( const vec3_t v1 , const vec3_t v2 ) ;
extern void AddPointToBounds ( const vec3_t v , vec3_t mins , vec3_t maxs ) ;
extern void ClearBounds ( vec3_t mins , vec3_t maxs ) ;
extern float RadiusFromBounds ( const vec3_t mins , const vec3_t maxs ) ;
extern int BoxOnPlaneSide ( vec3_t emins , vec3_t emaxs , cplane_t * p ) ;
extern void SetPlaneSignbits ( cplane_t * out ) ;
extern float AngleDelta ( float angle1 , float angle2 ) ;
extern float AngleNormalize180 ( float angle ) ;
extern float AngleNormalize360 ( float angle ) ;
extern float AngleMod ( float a ) ;
extern void AnglesSubtract ( vec3_t v1 , vec3_t v2 , vec3_t v3 ) ;
extern float AngleSubtract ( float a1 , float a2 ) ;
extern float LerpAngle ( float from , float to , float frac ) ;
extern float Q_fabs ( float f ) ;
extern float Q_rsqrt ( float number ) ;
extern void VectorRotate ( vec3_t in , vec3_t matrix [ 3 ] , vec3_t out ) ;
extern void MakeNormalVectors ( const vec3_t forward , vec3_t right , vec3_t up ) ;
extern void ProjectPointOnPlane ( vec3_t dst , const vec3_t p , const vec3_t normal ) ;
extern void AxisCopy ( vec3_t in [ 3 ] , vec3_t out [ 3 ] ) ;
extern void AxisClear ( vec3_t axis [ 3 ] ) ;
extern void AnglesToAxis ( const vec3_t angles , vec3_t axis [ 3 ] ) ;
extern void vectoangles ( const vec3_t value1 , vec3_t angles ) ;
extern void RotateAroundDirection ( vec3_t axis [ 3 ] , float yaw ) ;
extern void RotatePointAroundVector ( vec3_t dst , const vec3_t dir , const vec3_t point , float degrees ) ;
extern bool PlaneFromPoints ( vec4_t plane , const vec3_t a , const vec3_t b , const vec3_t c ) ;
extern float NormalizeColor ( const vec3_t in , vec3_t out ) ;
extern unsigned ColorBytes4 ( float r , float g , float b , float a ) ;
extern unsigned ColorBytes3 ( float r , float g , float b ) ;
extern void ByteToDir ( int b , vec3_t dir ) ;
extern int DirToByte ( vec3_t dir ) ;
extern signed short ClampShort ( int i ) ;
extern signed char ClampChar ( int i ) ;
extern float Q_crandom ( int * seed ) ;
extern float Q_random ( int * seed ) ;
extern int Q_rand ( int * seed ) ;
extern void G_SpawnEntitiesFromString ( void ) ;
extern void SP_worldspawn ( void ) ;

extern char * G_AddSpawnVarToken ( const char * string ) ;
extern void G_SpawnGEntityFromSpawnVars ( void ) ;
extern void G_ParseField ( const char * key , const char * value , GameEntity * ent ) ;
extern char * G_NewString ( const char * string ) ;
extern bool G_CallSpawn ( GameEntity * ent ) ;
extern bool G_SpawnVector ( const char * key , const char * defaultString , float * out ) ;
extern bool G_SpawnInt ( const char * key , const char * defaultString , int * out ) ;
extern bool G_SpawnFloat ( const char * key , const char * defaultString , float * out ) ;
extern bool G_SpawnString ( const char * key , const char * defaultString , const char * * out ) ;
extern void AICast_IdleReload ( cast_state_t * cs ) ;
extern void AICast_DeadClipWalls ( cast_state_t * cs ) ;
extern void AICast_QueryThink ( cast_state_t * cs ) ;
extern bool AICast_RequestCrouchAttack ( cast_state_t * cs , vec3_t org , float time ) ;
extern void AICast_EvaluatePmove ( int clientnum , pmove_t * pm ) ;
extern void AICast_Blocked ( cast_state_t * cs , bot_moveresult_t * moveresult , int activate , bot_goal_t * goal ) ;
extern bool AICast_GetAvoid ( cast_state_t * cs , bot_goal_t * goal , vec3_t outpos , bool reverse , int blockEnt ) ;
extern void AICast_PredictMovement ( cast_state_t * cs , int numframes , float frametime , aicast_predictmove_t * move , UserCmd * ucmd , int checkHitEnt ) ;
extern void AICast_StartServerFrame ( int time ) ;
extern void AICast_StartFrame ( int time ) ;
extern void AICast_Think ( int client , float thinktime ) ;
extern void AICast_UpdateInput ( cast_state_t * cs , int time ) ;
extern void AICast_InputToUserCommand ( cast_state_t * cs , bot_input_t * bi , UserCmd * ucmd , int delta_angles [ 3 ] ) ;
extern void AICast_ChangeViewAngles ( cast_state_t * cs , float thinktime ) ;
extern void AICast_ProcessAIFunctions ( cast_state_t * cs , float thinktime ) ;
extern void SP_alarm_box ( GameEntity * ent ) ;
extern void alarmbox_finishspawning ( GameEntity * ent ) ;
extern void alarmbox_die ( GameEntity * ent , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void alarmbox_use ( GameEntity * ent , GameEntity * other , GameEntity * foo ) ;
extern void alarmbox_updateparts ( GameEntity * ent , bool matestoo ) ;
extern void alarmExplosion ( GameEntity * ent ) ;
extern void ClientEndFrame ( GameEntity * ent ) ;

extern void G_RunClient ( GameEntity * ent ) ;
extern void ClientThink ( int clientNum ) ;
extern void ClientThink_real ( GameEntity * ent ) ;
extern void SendPendingPredictableEvents ( PlayerState * ps ) ;
extern void ClientEvents ( GameEntity * ent , int oldEventSequence ) ;
extern void ClientIntermissionThink ( GameClient * client ) ;
extern void ClientTimerActions ( GameEntity * ent , int msec ) ;


extern void G_TouchTriggers ( GameEntity * ent ) ;
extern void ClientImpacts ( GameEntity * ent , pmove_t * pm ) ;
extern void G_SetClientSound ( GameEntity * ent ) ;
extern void P_WorldEffects ( GameEntity * ent ) ;
extern void P_DamageFeedback ( GameEntity * player ) ;
extern bool ConsoleCommand ( void ) ;

extern GameClient * ClientForString ( const char * s ) ;
extern void Svcmd_EntityList_f ( void ) ;

extern void G_Activate ( GameEntity * ent , GameEntity * activator ) ;
extern void func_invisible_user ( GameEntity * ent ) ;
extern void use_invisible_user ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_func_explosive ( GameEntity * ent ) ;
extern void InitExplosive ( GameEntity * ent ) ;
extern void func_explosive_spawn ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void func_explosive_alert ( GameEntity * self ) ;
extern void func_explosive_use ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void func_explosive_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void func_explosive_explode ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void ClearExplosive ( GameEntity * self ) ;
extern void ThrowDebris ( GameEntity * self , char * modelname , float speed , vec3_t origin ) ;
extern void SP_target_effect ( GameEntity * ent ) ;
extern void use_target_effect ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void SP_func_door_rotating ( GameEntity * ent ) ;
extern void SP_func_pendulum ( GameEntity * ent ) ;
extern void SP_func_bobbing ( GameEntity * ent ) ;
extern void SP_func_rotating ( GameEntity * ent ) ;
extern void Use_Func_Rotate ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_func_static ( GameEntity * ent ) ;
extern void SP_func_leaky ( GameEntity * ent ) ;
extern void G_BlockThink ( GameEntity * ent ) ;
extern void Static_Pain ( GameEntity * ent , GameEntity * attacker , int damage , vec3_t point ) ;
extern void Use_Static ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_func_train_rotating ( GameEntity * self ) ;
extern void Think_SetupTrainTargets_rotating ( GameEntity * ent ) ;
extern void Reached_Train_rotating ( GameEntity * ent ) ;
extern void Think_BeginMoving_rotating ( GameEntity * ent ) ;
extern void SP_func_bats ( GameEntity * self ) ;
extern void FuncEndSpiritsThink ( GameEntity * self ) ;
extern void FuncBatsActivate ( GameEntity * self , GameEntity * other , GameEntity * activator ) ;
extern void BatDie ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int meansOfDeath ) ;
extern void BatMoveThink ( GameEntity * bat ) ;
extern void FuncBatsReached ( GameEntity * self ) ;
extern void SP_func_train_particles ( GameEntity * self ) ;
extern void Func_train_particles_reached ( GameEntity * self ) ;
extern void SP_func_train ( GameEntity * self ) ;
extern void SP_path_corner ( GameEntity * self ) ;
extern void Think_SetupTrainTargets ( GameEntity * ent ) ;
extern void Reached_Train ( GameEntity * ent ) ;
extern void Think_BeginMoving ( GameEntity * ent ) ;
extern void SP_func_button ( GameEntity * ent ) ;
extern void Touch_Button ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_func_plat ( GameEntity * ent ) ;
extern void SpawnPlatTrigger ( GameEntity * ent ) ;
extern void Touch_PlatCenterTrigger ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void Touch_Plat ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_func_secret ( GameEntity * ent ) ;
extern void SP_func_door ( GameEntity * ent ) ;
extern void G_TryDoor ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void DoorSetSounds ( GameEntity * ent , int doortype , bool isRotating ) ;
extern void Door_reverse_sounds ( GameEntity * ent ) ;
extern void finishSpawningKeyedMover ( GameEntity * ent ) ;
extern bool findNonAIBrushTargeter ( GameEntity * ent ) ;
extern void Think_MatchTeam ( GameEntity * ent ) ;
extern void Think_SpawnNewDoorTrigger ( GameEntity * ent ) ;
extern void Touch_DoorTrigger ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void Blocked_DoorRotate ( GameEntity * ent , GameEntity * other ) ;
extern void Blocked_Door ( GameEntity * ent , GameEntity * other ) ;
extern void InitMoverRotate ( GameEntity * ent ) ;
extern void InitMover ( GameEntity * ent ) ;
extern void Use_BinaryMover ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Use_TrinaryMover ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Reached_TrinaryMover ( GameEntity * ent ) ;
extern bool IsBinaryMoverBlocked ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Reached_BinaryMover ( GameEntity * ent ) ;
extern void ReturnToPos1Rotate ( GameEntity * ent ) ;
extern void GotoPos3 ( GameEntity * ent ) ;
extern void ReturnToPos2 ( GameEntity * ent ) ;
extern void ReturnToPos1 ( GameEntity * ent ) ;
extern void MatchTeamReverseAngleOnSlaves ( GameEntity * teamLeader , int moverState , int time ) ;
extern void MatchTeam ( GameEntity * teamLeader , int moverState , int time ) ;
extern void SetMoverState ( GameEntity * ent , moverState_t moverState , int time ) ;
extern void G_RunMover ( GameEntity * ent ) ;
extern void G_MoverTeam ( GameEntity * ent ) ;
extern bool G_MoverPush ( GameEntity * pusher , vec3_t move , vec3_t amove , GameEntity * * obstacle ) ;
extern bool G_TryPushingEntity ( GameEntity * check , GameEntity * pusher , vec3_t move , vec3_t amove ) ;
extern void G_RotatePoint ( vec3_t point , vec3_t matrix [ 3 ] ) ;
extern void G_TransposeMatrix ( vec3_t matrix [ 3 ] , vec3_t transpose [ 3 ] ) ;
extern void G_CreateRotationMatrix ( const vec3_t angles , vec3_t matrix [ 3 ] ) ;
extern void G_TestEntityMoveTowardsPos ( GameEntity * ent , vec3_t pos ) ;
extern void G_TestEntityDropToFloor ( GameEntity * ent , float maxdrop ) ;
extern GameEntity * G_TestEntityPosition ( GameEntity * ent ) ;
extern void G_LoadPersistant ( void ) ;
extern bool G_SavePersistant ( char * nextmap ) ;
extern void PersReadCastState ( fileHandle_t f , cast_state_t * cs ) ;
extern void PersWriteCastState ( fileHandle_t f , cast_state_t * cs ) ;
extern void PersReadEntity ( fileHandle_t f , GameEntity * cl ) ;
extern void PersWriteEntity ( fileHandle_t f , GameEntity * ent ) ;
extern void PersReadClient ( fileHandle_t f , GameClient * cl ) ;
extern void PersWriteClient ( fileHandle_t f , GameClient * cl ) ;
extern void G_LoadGame ( const char * filename ) ;
extern bool G_SaveGame ( const char * username ) ;
extern char * G_Save_DateStr ( void ) ;
extern char * G_Save_TimeStr ( void ) ;
extern void ReadTime ( fileHandle_t f , qtime_t * tm ) ;
extern void WriteTime ( fileHandle_t f ) ;
extern void ReadCastState ( fileHandle_t f , cast_state_t * cs , int size ) ;
extern void WriteCastState ( fileHandle_t f , cast_state_t * cs ) ;
extern void ReadEntity ( fileHandle_t f , GameEntity * ent , int size ) ;
extern void WriteEntity ( fileHandle_t f , GameEntity * ent ) ;
extern void ReadClient ( fileHandle_t f , GameClient * client , int size ) ;
extern void WriteClient ( fileHandle_t f , GameClient * cl ) ;
extern void G_Save_Decode ( uint8_t * in , int insize , uint8_t * out , int outsize ) ;
extern int G_Save_Encode ( uint8_t * raw , uint8_t * out , int rawsize , int outsize ) ;
extern void ReadField ( fileHandle_t f , saveField_t * field , uint8_t * base ) ;
extern void WriteField2 ( fileHandle_t f , saveField_t * field , uint8_t * base ) ;
extern void WriteField1 ( saveField_t * field , uint8_t * base ) ;
extern uint8_t * G_FindFuncByName ( char * name ) ;
extern funcList_t * G_FindFuncAtAddress ( uint8_t * adr ) ;
extern int G_SaveWrite ( const void * buffer , int len , fileHandle_t f ) ;
extern void G_SaveWriteError ( void ) ;
extern void PM_StepSlideMove ( bool gravity ) ;
extern bool PM_SlideMove ( bool gravity ) ;
extern void SP_camera_reset_player ( GameEntity * ent ) ;
extern void reset_players_pos ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void mark_players_pos ( GameEntity * ent , GameEntity * other , trace_t * trace ) ;
extern void SP_screen_fade ( GameEntity * ent ) ;
extern void screen_fade_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void SP_camera_cam ( GameEntity * ent ) ;
extern void camera_cam_firstthink ( GameEntity * ent ) ;
extern void camera_cam_use ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void camera_cam_think ( GameEntity * ent ) ;
extern void Init_Camera ( GameEntity * ent ) ;
extern void delayOnthink ( GameEntity * ent ) ;
extern void SP_truck_cam ( GameEntity * self ) ;
extern void truck_cam_think ( GameEntity * ent ) ;
extern void truck_cam_touch ( GameEntity * self , GameEntity * other , trace_t * trace ) ;
extern void SP_props_me109 ( GameEntity * ent ) ;
extern void InitPlaneSpeaker ( GameEntity * ent ) ;
extern void PlaneUse ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Think_SetupAirplaneWaypoints ( GameEntity * ent ) ;
extern void props_me109_think ( GameEntity * self ) ;
extern void Plane_Attack ( GameEntity * self , bool in_PVS ) ;
extern void Plane_Fire_Lead ( GameEntity * self ) ;
extern void props_me109_pain ( GameEntity * self , GameEntity * attacker , int damage , vec3_t point ) ;
extern void props_me109_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void ExplodePlaneSndFx ( GameEntity * self ) ;
extern void SP_plane_waypoint ( GameEntity * self ) ;
extern void plane_AIScript_AlertEntity ( GameEntity * ent ) ;
extern void SP_func_tramcar ( GameEntity * self ) ;
extern void Blocked_Tramcar ( GameEntity * ent , GameEntity * other ) ;
extern void TramCarUse ( GameEntity * ent , GameEntity * other , GameEntity * activator ) ;
extern void Tramcar_die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int mod ) ;
extern void Reached_Tramcar ( GameEntity * ent ) ;
extern void GetNextTrack ( GameEntity * ent ) ;
extern void Calc_Roll ( GameEntity * ent ) ;
extern void InitTramcar ( GameEntity * ent ) ;
extern void AICast_RecordScriptSound ( int client ) ;
extern void AICast_ProcessActivate ( int entNum , int activatorNum ) ;
extern void AICast_AIDoor_Touch ( GameEntity * ent , GameEntity * aidoor_trigger , GameEntity * door ) ;
extern void AICast_EndChase ( cast_state_t * cs ) ;
extern void AICast_Die ( GameEntity * self , GameEntity * inflictor , GameEntity * attacker , int damage , int meansOfDeath ) ;
extern void AICast_Pain ( GameEntity * targ , GameEntity * attacker , int damage , vec3_t point ) ;
extern void AICast_Sight ( GameEntity * ent , GameEntity * other , int lastSight ) ;
extern const char * AIFunc_WarriorZombieDefenseStart ( cast_state_t * cs ) ;
extern const char * AIFunc_WarriorZombieDefense ( cast_state_t * cs ) ;
extern const char * AIFunc_WarriorZombieSightStart ( cast_state_t * cs ) ;
extern const char * AIFunc_WarriorZombieSight ( cast_state_t * cs ) ;
extern const char * AIFunc_WarriorZombieMeleeStart ( cast_state_t * cs ) ;
extern const char * AIFunc_WarriorZombieMelee ( cast_state_t * cs ) ;
extern const char * AIFunc_RejectAttack1Start ( cast_state_t * cs ) ;
extern const char * AIFunc_RejectAttack1 ( cast_state_t * cs ) ;
extern const char * AIFunc_BlackGuardAttack1Start ( cast_state_t * cs ) ;
extern const char * AIFunc_BlackGuardAttack1 ( cast_state_t * cs ) ;
extern const char * AIFunc_StimSoldierAttack2Start ( cast_state_t * cs ) ;
extern const char * AIFunc_StimSoldierAttack2 ( cast_state_t * cs ) ;
extern const char * AIFunc_StimSoldierAttack1Start ( cast_state_t * cs ) ;
extern const char * AIFunc_StimSoldierAttack1 ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack3Start ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack3 ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack2Start ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack2 ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack1Start ( cast_state_t * cs ) ;
extern const char * AIFunc_LoperAttack1 ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieMeleeStart ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieMelee ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieAttack2Start ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieAttack2 ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieFlameAttackStart ( cast_state_t * cs ) ;
extern const char * AIFunc_ZombieFlameAttack ( cast_state_t * cs ) ;
extern void SP_ai_blackguard ( GameEntity * ent ) ;
extern void SP_ai_protosoldier ( GameEntity * ent ) ;
extern void SP_ai_supersoldier ( GameEntity * ent ) ;
extern void SP_ai_stimsoldier_tesla ( GameEntity * ent ) ;
extern void SP_ai_stimsoldier_rocket ( GameEntity * ent ) ;
extern void SP_ai_stimsoldier_dual ( GameEntity * ent ) ;
extern void SP_ai_frogman ( GameEntity * ent ) ;
extern void SP_ai_eliteguard ( GameEntity * ent ) ;
extern void SP_ai_civilian ( GameEntity * ent ) ;
extern void SP_ai_partisan ( GameEntity * ent ) ;
extern void SP_ai_boss_heinrich ( GameEntity * ent ) ;
extern void SP_ai_boss_helga ( GameEntity * ent ) ;
extern void SP_ai_loper ( GameEntity * ent ) ;
extern void SP_ai_venom ( GameEntity * ent ) ;
extern void SP_ai_warzombie ( GameEntity * ent ) ;
extern void SP_ai_zombie ( GameEntity * ent ) ;
extern void SP_ai_american ( GameEntity * ent ) ;
extern void SP_ai_soldier ( GameEntity * ent ) ;
extern void AIChar_spawn ( GameEntity * ent ) ;
extern void AIChar_AttackSound ( cast_state_t * cs ) ;
extern void AIChar_Sight ( GameEntity * ent , GameEntity * other , int lastSight ) ;
extern void AIChar_Pain ( GameEntity * ent , GameEntity * attacker , int damage , vec3_t point ) ;
extern int AIChar_GetPainLocation ( GameEntity * ent , vec3_t point ) ;
extern void AIChar_Death ( GameEntity * ent , GameEntity * attacker , int damage , int mod ) ;
extern void AIChar_SetBBox ( GameEntity * ent , cast_state_t * cs , bool useHeadTag ) ;
